# Generated by Django 3.1.6 on 2021-02-09 14:31

from django.db import migrations, models
import habits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Compound username made up of the email address and the company ID.<br/>Internal use only - user never sees this', max_length=255, unique=True)),
                ('global_id', models.CharField(blank=True, db_index=True, default=habits.models.generate_global_user_id, max_length=100, unique=True, verbose_name='Globally unique ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='last name')),
                ('require_password_change', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
