# Generated by Django 3.1.6 on 2021-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='one_word_label',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
